# b站推送，1 开启 0 关闭，保留添加的相关数据，但是不再推送
pushStatus: 1

# 检测b站动态的周期，Cron表达式，作用域共6位，具体方法浏览器搜索 “node-schedule cron表达式”，示例：
# "*/15  * * * *" #每15min检测一次
# "*/31  * * * *" #每31min检测一次
# "0 5,35 * * * *" #每小时固定第5分0秒、第35分0秒检测一次，共2次/h
# "0 5,35,51 * * * *" #每小时固定第5分0秒、第35分0秒、第51分0秒检测一次，共3次/h
pushTime: '*/23  * * * *'

# 推送监测间隔，单位为秒，默认7200秒即2小时，即以当前时间为基准，监测过去2小时内的动态，并推送。取值范围：3600-36000秒，即过去的1-10h。应大于pushTime的周期。
interval: 7200

# 全部订阅的转发动态是否推送： 默认 1 - 开启推送， 0 - 关闭推送。 如果仅仅需要关闭单个订阅的转发动态推送，使用分类订阅指令不包含 转发 分类即可，无需修改此配置。
pushTransmit: 1

# 推送动态时，限制发送多少张图片
pushPicCountLimit: 3

# 推送文字和图文动态时，限制字数是多少
pushContentLenLimit: 100

# 推送文字和图文动态时，限制多少行文本
pushContentLineLimit: 5

# 是否展示定时任务的日志，0 不显示 1 显示
pushTaskLog: 1

# 包含关键词不推送
banWords:
  - 关键词1
  - 关键词2

# 设置B站动态消息模式 0 文字模式 1 图片模式
pushMsgMode: 1

# 是否启用九宫格样式：默认 1 启用，0 不启用。此为最高优先级，九宫格为动态模式，特定大小/长宽比的图片资源将会动态启用九宫格/四宫格/无宫格样式。
boxGrid: 1

# B站动态卡片分片截图模式：默认 1 启用 0 不启用。启用，将会推送每条动态的全部内容；不启用，动态内容过长时候将只推送noSplitHeight长度的动态卡片，需关闭宫格模式。
isSplit: 1

# 动态卡片非分片模式下的截图高度，默认7500px（仅填数字，无需填入单位），请勿设置过大或过小。关闭分片截图时生效。
noSplitHeight: 7500

# 动态卡片分页截图高度，默认8000px（仅填数字，无需填入单位），请勿设置过大或过小。启用分片截图时生效。
splitHeight: 8000
